// 14-advanced/vue-fundamentals/src/components/Profile.vue
<template>
  <div>
    <div class="profile">
      <h2>{{ name }}</h2>
      <h3>{{ bio }}</h3>
      <div>
        <button @click="zoomIn"> + </button>
        <button @click="zoomOut"> - </button>
      </div>
      <img v-if="size > 0" v-bind:src="pic" v-bind:alt="name" v-bind:height="size" />
    </div>
  </div>
</template>

<script>
export default {
  name: 'Profile',
  props: {
    name: String,
    bio: String,
    pic: String
  },
  data() {
    return {
      size: 100
    }
  },
  methods: {
    zoomIn() {
      this.size += 10;
    },
    zoomOut() {
      this.size -= 10;
    }
  }
}
</script>

<style lang="css" scoped>
</style>

// 13-react/social-network/src/components/Profile.js
import React, { Component } from 'react';

class Profile extends Component {
  constructor() {
    super();

    this.state = {
      height: 100 // initial value
    }

    this._zoomIn = this._zoomIn.bind(this); // This just makes it work.
    this._zoomOut = this._zoomOut.bind(this); // This just makes it work.
  }

  _zoomIn() {
    this.setState({height: this.state.height + 10});
  }

  _zoomOut() {
    this.setState({height: this.state.height - 10});
  }

  render() {
    const { name, age, motto, pic } = this.props;

    return (
      <div>
        <h2>{ name }</h2>
        <h3>Age: { age }</h3>
        <p>{ motto }</p>

        <div>
          <button onClick={ this._zoomIn }> + </button>
          <button onClick={ this._zoomOut }> - </button>
        </div>
        <img src={ pic } alt={ name } height={ this.state.height } />
      </div>
    );
  }
}

export default Profile;
